Update Arachni.yml

diff --git a/.github/workflows/Arachni.yml b/.github/workflows/Arachni.yml
--- a/.github/workflows/Arachni.yml
+++ b/.github/workflows/Arachni.yml
@@ -26,32 +26,36 @@ jobs:
 
       - name: Start Flask Application
         run: |
-          python Backend/__init__.py &
+          python Backend/__init__.py --host=0.0.0.0 &
           echo $! > flask_pid.txt
           sleep 10
 
       - name: Run Arachni Scanner
         run: |
-          # Instalar dependencias necesarias para Arachni
+          # Limpieza del entorno para liberar espacio
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
           sudo apt update
           sudo apt install -y libcurl4 libxml2 libxslt-dev zlib1g-dev
 
           # Descargar Arachni
           curl -L https://github.com/Arachni/arachni/releases/download/v1.6.1.3/Arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz -o arachni.tar.gz
 
-          # Verificar y descomprimir el archivo
+          # Validar y descomprimir el archivo
           if file arachni.tar.gz | grep -q 'gzip compressed data'; then
               echo "Archivo válido, procediendo a descomprimir..."
-              tar -xzf arachni.tar.gz
-              extracted_dir=$(tar -tzf arachni.tar.gz | head -1 | cut -f1 -d"/")
-              mv "$extracted_dir" arachni
+              tar -xvzf arachni.tar.gz
           else
-              echo "Error: El archivo descargado no es válido"
-              exit 1
+              echo "Error: El archivo descargado no es válido"; exit 1
           fi
 
-          # Ejecutar Arachni
-          ./arachni/bin/arachni http://127.0.0.1:5000 --report-save-path=arachni_report.afr
+          # Detectar el directorio descomprimido y moverlo
+          extracted_dir=$(tar -tzf arachni.tar.gz | head -1 | cut -f1 -d"/")
+          echo "Directorio detectado: $extracted_dir"
+          mv "$extracted_dir" arachni
+
+          # Ejecutar Arachni con una dirección válida
+          ./arachni/bin/arachni http://0.0.0.0:5000 --report-save-path=arachni_report.afr
 
       - name: Convert Arachni Report to HTML
         run: |
