Fix Arachni.yml

diff --git a/.github/workflows/Arachni.yml b/.github/workflows/Arachni.yml
--- a/.github/workflows/Arachni.yml
+++ b/.github/workflows/Arachni.yml
@@ -35,27 +35,23 @@ jobs:
           # Instalar dependencias necesarias para Arachni
           sudo apt update
           sudo apt install -y libcurl4 libxml2 libxslt-dev zlib1g-dev
-          
-          # Descargar Arachni desde la fuente oficial
+
+          # Descargar Arachni
           curl -L https://github.com/Arachni/arachni/releases/download/v1.6.1.3/Arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz -o arachni.tar.gz
-          
-          # Verificar que el archivo sea válido
+
+          # Verificar y descomprimir el archivo
           if file arachni.tar.gz | grep -q 'gzip compressed data'; then
               echo "Archivo válido, procediendo a descomprimir..."
-              tar -xvzf arachni.tar.gz
+              tar -xzf arachni.tar.gz
+              extracted_dir=$(tar -tzf arachni.tar.gz | head -1 | cut -f1 -d"/")
+              mv "$extracted_dir" arachni
           else
-              echo "Error: El archivo descargado no es válido"; exit 1
+              echo "Error: El archivo descargado no es válido"
+              exit 1
           fi
-          
-          # Detectar el directorio descomprimido
-          extracted_dir=$(tar -tzf arachni.tar.gz | head -1 | cut -f1 -d"/")
-          echo "Directorio detectado: $extracted_dir"
-          
-          # Mover el directorio al nombre esperado
-          mv "$extracted_dir" arachni
-          
+
           # Ejecutar Arachni
-          ./arachni/bin/arachni http://127.0.0.1:5000 --output-file=arachni_report.afr
+          ./arachni/bin/arachni http://127.0.0.1:5000 --report-save-path=arachni_report.afr
 
       - name: Convert Arachni Report to HTML
         run: |
