Fix: Arachni.yml

diff --git a/.github/workflows/Arachni.yml b/.github/workflows/Arachni.yml
--- a/.github/workflows/Arachni.yml
+++ b/.github/workflows/Arachni.yml
@@ -34,9 +34,14 @@ jobs:
         run: |
           sudo apt update
           sudo apt install -y libcurl4 libxml2 libxslt-dev zlib1g-dev
-          curl -L https://github.com/Arachni/arachni/releases/download/v1.6.1-0.6.1/arachni-1.6.1-0.6.1-linux-x86_64.tar.gz -o arachni.tar.gz
-          tar -xvzf arachni.tar.gz
-          mv arachni-1.6.1-0.6.1/ arachni
+          curl -L https://github.com/Arachni/arachni/releases/download/v1.6.1.3/Arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz -o arachni.tar.gz
+          if file arachni.tar.gz | grep -q 'gzip compressed data'; then
+              echo "Archivo válido, procediendo a descomprimir..."
+              tar -xvzf arachni.tar.gz
+              mv Arachni-1.6.1.3-0.6.1.1/ arachni
+          else
+              echo "Error: El archivo descargado no es válido"; exit 1
+          fi
           ./arachni/bin/arachni http://127.0.0.1:5000 --output-file=arachni_report.afr
 
       - name: Convert Arachni Report to HTML
